Repository AY2223S1-CS2103T-W15-1/tp, pull requests merged in 2022-11, with the labels that each got.

#219 Search Feature and Documentation related bug fix
  docs/UserGuide.md
  src/main/java/soconnect/commons/util/StringUtil.java
  src/main/java/soconnect/logic/commands/SearchCommand.java
  src/main/java/soconnect/logic/parser/SearchCommandParser.java
  src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java
  src/test/java/soconnect/commons/util/StringUtilTest.java
  src/test/java/soconnect/logic/commands/SearchCommandTest.java
  src/test/java/soconnect/logic/parser/SearchCommandParserTest.java
Labels: priority.High

#220 PE-D Fixes
  docs/UserGuide.md
  src/main/java/soconnect/commons/core/Messages.java
  src/main/java/soconnect/logic/commands/ListCommand.java
  src/main/java/soconnect/model/person/Email.java
Labels: bug, documentation, priority.High

#221 Week 12: Update PPP Documentation
  docs/team/florentianayuwono.md
Labels: priority.High

#223 Add details to PPP
  docs/team/eugene-ong-w-x.md
Labels: documentation, priority.High

#225 Update PPP
  docs/team/ugholaf.md
Labels: documentation

#216 Fix PED bugs
  src/main/java/soconnect/commons/core/Messages.java
  src/main/java/soconnect/logic/autocomplete/Autocomplete.java
  src/main/java/soconnect/logic/commands/todo/TodoShowCommand.java
  src/main/java/soconnect/logic/parser/todo/TodoShowCommandParser.java
  src/main/java/soconnect/model/todo/Date.java
  src/main/java/soconnect/ui/CommandBox.java
  src/main/java/soconnect/ui/TodoListPanel.java
Labels: bug, documentation, priority.High

#224 Enable contact and attributes wrapping
  src/main/java/soconnect/ui/PersonCard.java
  src/main/java/soconnect/ui/TodoCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/SoConnectTheme.css
Labels: priority.High

#237 Fix bug and code quality
  src/main/java/soconnect/logic/commands/customise/CustomiseCommand.java
  src/main/java/soconnect/ui/PersonCard.java
Labels: bug, priority.High

#217 Updates based on peer review
  docs/UserGuide.md
  src/main/java/soconnect/logic/commands/ClearCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagEditCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagRemoveCommand.java
  src/main/java/soconnect/logic/parser/ParserUtil.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/person/Address.java
  src/main/java/soconnect/model/person/Email.java
  src/main/java/soconnect/model/person/Name.java
  src/main/java/soconnect/model/person/Phone.java
  src/main/java/soconnect/model/tag/Tag.java
  src/main/java/soconnect/storage/JsonAdaptedTag.java
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
  src/test/java/soconnect/model/person/EmailTest.java
Labels: bug, documentation, priority.High

#241 UG: Front Matters, Formatting and Restructuring
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/initialize.scss
Labels: documentation, priority.High

#249 Update User Guide (Command Format, CLI, Summary Table), developer guide use cases and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/pangkuangwei.md
Labels: documentation, priority.High

#251 Revamp Commands section and FAQ section
  docs/UserGuide.md
  docs/team/florentianayuwono.md
  docs/team/ugholaf.md
Labels: documentation, priority.High

#250 Update UG and PPP
  docs/UserGuide.md
  docs/team/chongcheekaiclarence.md
Labels: documentation

#252 Remove bindings
  src/main/java/soconnect/ui/PersonCard.java
  src/main/java/soconnect/ui/TodoCard.java
Labels: bug

#255 Fix hyperlink and add screenshot placeholders
  docs/UserGuide.md
Labels: documentation

#253 DG: Manual Testing Instructions, Test Cases and Effort
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/florentianayuwono.md
  src/main/java/soconnect/logic/commands/SearchCommand.java
Labels: documentation, priority.High

#257 Fix PPP
  docs/team/pangkuangwei.md
Labels: documentation

#260 Add UML diagram to autocomplete and update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AutocompleteActivityDiagram.puml
  docs/diagrams/AutocompleteClasses.puml
  docs/diagrams/AutocompleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AutocompleteActivityDiagram.png
  docs/images/AutocompleteClasses.png
  docs/images/AutocompleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/img.png
  docs/team/ugholaf.md
Labels: documentation
