Repository AY2223S1-CS2103T-W15-1/tp, pull requests merged in 2022-10, with the labels that each got.

#36 Branch tag features
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/TagCreateCommand.java
  src/main/java/seedu/address/logic/commands/TagEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagAddCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCreateCommandParser.java
  src/main/java/seedu/address/logic/parser/TagEditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: enhancement, priority.High

#37 Add customise order feature
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/CustomiseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CustomiseCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/CustomiseCommandTest.java
  src/test/java/seedu/address/logic/parser/CustomiseCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, priority.High

#42 Add customise hide and customise show feature
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/CustomiseCommand.java
  src/main/java/seedu/address/logic/parser/CustomiseCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CustomiseCommandTest.java
  src/test/java/seedu/address/logic/parser/CustomiseCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, priority.High

#41 Add autocomplete feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/autocomplete/Autocomplete.java
  src/main/java/seedu/address/logic/autocomplete/AutocompleteManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/address/logic/autocomplete/AutocompleteManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: enhancement, priority.Medium

#43 Fix for User Stories table in DG: Attempt 1
  docs/DeveloperGuide.md
Labels: bug, documentation

#45 Fix incorrect glossary format
  docs/DeveloperGuide.md
Labels: bug, documentation

#63 Fix Sorting bug
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: bug

#59 Week 9 / V1.2 Documentation updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: documentation, priority.High

#67 Week 9 - Update UG documentation
  docs/UserGuide.md
Labels: documentation, priority.High

#65 Fix tag add bug where having no fields give an error
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/TagEditCommand.java
  src/main/java/seedu/address/logic/parser/TagAddCommandParser.java
  src/test/java/seedu/address/logic/parser/TagAddCommandParserTest.java
Labels: bug

#73 Fix bugs and add test cases for Search Feature
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ContactContainsAllKeywordsPredicate.java
  src/main/java/seedu/address/model/person/ContactContainsAnyKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: priority.High

#78 Format addressbook.json
  .gitignore
  data/addressbook.json
Labels: bug, priority.High

#68 Week 9 Documentation Updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation, priority.Medium

#75 Documentation: Search Feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High

#103 Model and Storage upgraded for Todo functionality
  data/addressbook.json
  data/soconnect.json
  src/main/java/soconnect/MainApp.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/ReadOnlyTodoList.java
  src/main/java/soconnect/model/ReadOnlyUserPrefs.java
  src/main/java/soconnect/model/SoConnect.java
  src/main/java/soconnect/model/TodoList.java
  src/main/java/soconnect/model/UserPrefs.java
  src/main/java/soconnect/model/todo/Todo.java
  src/main/java/soconnect/model/todo/UniqueTodoList.java
  src/main/java/soconnect/model/todo/exceptions/DuplicateTodoException.java
  src/main/java/soconnect/model/todo/exceptions/TodoNotFoundException.java
  src/main/java/soconnect/model/util/SampleDataUtil.java
  src/main/java/soconnect/storage/JsonAdaptedTodo.java
  src/main/java/soconnect/storage/JsonSerializableTodoList.java
  src/main/java/soconnect/storage/JsonTodoListStorage.java
  src/main/java/soconnect/storage/Storage.java
  src/main/java/soconnect/storage/StorageManager.java
  src/main/java/soconnect/storage/TodoListStorage.java
  src/test/java/soconnect/logic/LogicManagerTest.java
  src/test/java/soconnect/logic/commands/AddCommandIntegrationTest.java
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/ClearCommandTest.java
  src/test/java/soconnect/logic/commands/CustomiseCommandTest.java
  src/test/java/soconnect/logic/commands/DeleteCommandTest.java
  src/test/java/soconnect/logic/commands/EditCommandTest.java
  src/test/java/soconnect/logic/commands/FindCommandTest.java
  src/test/java/soconnect/logic/commands/ListCommandTest.java
  src/test/java/soconnect/logic/commands/SearchCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
  src/test/java/soconnect/logic/commands/TagAddCommandTest.java
  src/test/java/soconnect/logic/commands/TagCreateCommandTest.java
  src/test/java/soconnect/logic/commands/TagEditCommandTest.java
  src/test/java/soconnect/logic/parser/CustomiseCommandParserTest.java
  src/test/java/soconnect/logic/parser/TagCommandParserTest.java
  src/test/java/soconnect/model/ModelManagerTest.java
  src/test/java/soconnect/storage/StorageManagerTest.java
Labels: enhancement, priority.High

#90 Add GUI for task management
  src/main/java/soconnect/logic/Logic.java
  src/main/java/soconnect/logic/LogicManager.java
  src/main/java/soconnect/model/todo/Todo.java
  src/main/java/soconnect/ui/MainDisplay.java
  src/main/java/soconnect/ui/MainWindow.java
  src/main/java/soconnect/ui/PersonCard.java
  src/main/java/soconnect/ui/TodoCard.java
  src/main/java/soconnect/ui/TodoListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/TodoListCard.fxml
  src/main/resources/view/TodoListPanel.fxml
Labels: enhancement, priority.High

#91 Refactor Customise Feature's code and remove border from non-tag attributes
  src/main/java/soconnect/commons/core/GuiSettings.java
  src/main/java/soconnect/logic/Logic.java
  src/main/java/soconnect/logic/LogicManager.java
  src/main/java/soconnect/logic/commands/customise/CustomiseCommand.java
  src/main/java/soconnect/logic/commands/customise/CustomiseHideCommand.java
  src/main/java/soconnect/logic/commands/customise/CustomiseOrderCommand.java
  src/main/java/soconnect/logic/commands/customise/CustomiseShowCommand.java
  src/main/java/soconnect/logic/parser/CustomiseCommandParser.java
  src/main/java/soconnect/logic/parser/SoConnectParser.java
  src/main/java/soconnect/logic/parser/customise/CustomiseCommandParser.java
  src/main/java/soconnect/logic/parser/customise/CustomiseHideCommandParser.java
  src/main/java/soconnect/logic/parser/customise/CustomiseOrderCommandParser.java
  src/main/java/soconnect/logic/parser/customise/CustomiseShowCommandParser.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/UserPrefs.java
  src/main/java/soconnect/ui/MainWindow.java
  src/main/java/soconnect/ui/PersonCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/CustomiseCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
  src/test/java/soconnect/logic/commands/customise/CustomiseHideCommandTest.java
  src/test/java/soconnect/logic/commands/customise/CustomiseOrderCommandTest.java
  src/test/java/soconnect/logic/commands/customise/CustomiseShowCommandTest.java
  src/test/java/soconnect/logic/parser/CustomiseCommandParserTest.java
  src/test/java/soconnect/logic/parser/customise/CustomiseCommandParserTest.java
  src/test/java/soconnect/logic/parser/customise/CustomiseHideCommandParserTest.java
  src/test/java/soconnect/logic/parser/customise/CustomiseOrderCommandParserTest.java
  src/test/java/soconnect/logic/parser/customise/CustomiseShowCommandParserTest.java
Labels: priority.Medium

#104 Search Feature
  src/main/java/soconnect/commons/util/StringUtil.java
  src/main/java/soconnect/logic/commands/SearchCommand.java
  src/main/java/soconnect/logic/parser/ArgumentMultimap.java
  src/main/java/soconnect/logic/parser/SearchCommandParser.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/person/ContactContainsAllKeywordsPredicate.java
  src/main/java/soconnect/model/person/search/ContactContainsAllKeywordsPredicate.java
  src/main/java/soconnect/model/person/search/ContactContainsAnyKeywordsPredicate.java
  src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java
  src/main/java/soconnect/model/person/search/SearchPrefix.java
  src/test/java/soconnect/commons/util/StringUtilTest.java
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/SearchCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
  src/test/java/soconnect/logic/parser/SearchCommandParserTest.java
Labels: type.Story, priority.High

#110 Enable assertions and updated build.gradle
  build.gradle
Labels: enhancement, priority.Medium

#106 Tag Features
  .gitignore
  data/soconnect.json
  docs/UserGuide.md
  src/main/java/soconnect/logic/commands/AddCommand.java
  src/main/java/soconnect/logic/commands/TagCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagAddCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagCreateCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagDeleteCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagEditCommand.java
  src/main/java/soconnect/logic/commands/tagcommands/TagRemoveCommand.java
  src/main/java/soconnect/logic/parser/AddCommandParser.java
  src/main/java/soconnect/logic/parser/SoConnectParser.java
  src/main/java/soconnect/logic/parser/tagcommandparsers/TagAddCommandParser.java
  src/main/java/soconnect/logic/parser/tagcommandparsers/TagCommandParser.java
  src/main/java/soconnect/logic/parser/tagcommandparsers/TagCreateCommandParser.java
  src/main/java/soconnect/logic/parser/tagcommandparsers/TagDeleteCommandParser.java
  src/main/java/soconnect/logic/parser/tagcommandparsers/TagEditCommandParser.java
  src/main/java/soconnect/logic/parser/tagcommandparsers/TagRemoveCommandParser.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/SoConnect.java
  src/main/java/soconnect/model/person/Person.java
  src/main/java/soconnect/model/person/UniquePersonList.java
  src/main/java/soconnect/model/tag/UniqueTagList.java
  src/main/java/soconnect/storage/JsonSerializableSoConnect.java
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
  src/test/java/soconnect/logic/commands/TagCommandTest.java
  src/test/java/soconnect/logic/commands/tagcommand/TagAddCommandTest.java
  src/test/java/soconnect/logic/commands/tagcommand/TagCreateCommandTest.java
  src/test/java/soconnect/logic/commands/tagcommand/TagEditCommandTest.java
  src/test/java/soconnect/logic/parser/tagcommandparser/TagAddCommandParserTest.java
  src/test/java/soconnect/logic/parser/tagcommandparser/TagCommandParserTest.java
  src/test/java/soconnect/logic/parser/tagcommandparser/TagCreateCommandParserTest.java
  src/test/java/soconnect/logic/parser/tagcommandparser/TagEditCommandParserTest.java
Labels: enhancement, priority.High

#107 Implement Todo commands
  data/todolist.json
  src/main/java/soconnect/MainApp.java
  src/main/java/soconnect/commons/core/Messages.java
  src/main/java/soconnect/logic/Logic.java
  src/main/java/soconnect/logic/LogicManager.java
  src/main/java/soconnect/logic/commands/todo/TodoAddCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoClearCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoDeleteCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoEditCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoShowCommand.java
  src/main/java/soconnect/logic/parser/CliSyntax.java
  src/main/java/soconnect/logic/parser/ParserUtil.java
  src/main/java/soconnect/logic/parser/SoConnectParser.java
  src/main/java/soconnect/logic/parser/todo/TodoAddCommandParser.java
  src/main/java/soconnect/logic/parser/todo/TodoDeleteCommandParser.java
  src/main/java/soconnect/logic/parser/todo/TodoEditCommandParser.java
  src/main/java/soconnect/logic/parser/todo/TodoParser.java
  src/main/java/soconnect/logic/parser/todo/TodoShowCommandParser.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/ReadOnlyTodoList.java
  src/main/java/soconnect/model/SoConnect.java
  src/main/java/soconnect/model/TodoList.java
  src/main/java/soconnect/model/person/UniquePersonList.java
  src/main/java/soconnect/model/todo/Description.java
  src/main/java/soconnect/model/todo/Priority.java
  src/main/java/soconnect/model/todo/Todo.java
  src/main/java/soconnect/model/todo/TodoContainsPriorityPredicate.java
  src/main/java/soconnect/model/todo/TodoContainsTagPredicate.java
  src/main/java/soconnect/model/todo/UniqueTodoList.java
  src/main/java/soconnect/model/todo/exceptions/DuplicateTodoException.java
  src/main/java/soconnect/model/todo/exceptions/TodoNotFoundException.java
  src/main/java/soconnect/model/util/SampleDataUtil.java
  src/main/java/soconnect/storage/JsonAdaptedTodo.java
  src/main/java/soconnect/storage/JsonSerializableTodoList.java
  src/main/java/soconnect/storage/JsonTodoListStorage.java
  src/main/java/soconnect/storage/Storage.java
  src/main/java/soconnect/storage/StorageManager.java
  src/main/java/soconnect/storage/TodoListStorage.java
  src/main/java/soconnect/ui/TodoCard.java
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
Labels: enhancement, priority.High

#112 Trial Release for v1.3
  src/main/java/soconnect/MainApp.java
Labels: priority.Medium

#109 Week 10: Update Developer Guide - Customise Order Feature
  docs/DeveloperGuide.md
  docs/diagrams/CustomiseOrderSequenceDiagram.puml
  docs/images/CustomiseOrderSequenceDiagram.png
Labels: documentation, priority.Medium

#122 Refactor Code
  src/main/java/soconnect/MainApp.java
  src/main/java/soconnect/logic/Logic.java
  src/main/java/soconnect/logic/commands/SortCommand.java
  src/main/java/soconnect/logic/parser/ArgumentTokenizer.java
  src/main/java/soconnect/logic/parser/SortCommandParser.java
  src/main/java/soconnect/logic/parser/todo/TodoEditCommandParser.java
  src/main/java/soconnect/logic/parser/todo/TodoParser.java
  src/main/java/soconnect/logic/parser/todo/TodoShowCommandParser.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/SoConnect.java
  src/main/java/soconnect/model/TodoList.java
  src/main/java/soconnect/model/person/UniquePersonList.java
  src/main/java/soconnect/model/tag/UniqueTagList.java
  src/main/java/soconnect/model/todo/UniqueTodoList.java
  src/main/java/soconnect/model/todo/exceptions/DuplicateTodoException.java
  src/main/java/soconnect/model/util/SampleDataUtil.java
  src/main/java/soconnect/storage/JsonAdaptedTodo.java
  src/main/java/soconnect/storage/JsonSerializableTodoList.java
  src/main/java/soconnect/storage/JsonTodoListStorage.java
  src/main/java/soconnect/storage/TodoListStorage.java
  src/main/java/soconnect/ui/TodoCard.java
Labels: enhancement, priority.Medium

#126 Update DG Part 1
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#125 Documentation improvement
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/index.md
Labels: priority.High

#127 Update developer guide with autocomplete implementation
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#128 UI Improvement
  src/main/java/soconnect/ui/UiManager.java
  src/main/resources/images/SoConnect_logo.png
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/SoConnectTheme.css
  src/main/resources/view/TodoListCard.fxml
  src/main/resources/view/TodoListPanel.fxml
  src/test/java/soconnect/commons/util/AppUtilTest.java
Labels: priority.High

#130 Minor GUI Adjustments
  src/main/java/soconnect/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/SoConnectTheme.css
  src/main/resources/view/TodoListCard.fxml
Labels: enhancement, priority.High

#131 v1.3 Docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/SortSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation, priority.High

#114 Add tagList into the sample data
  data/soconnect.json
  data/todolist.json
  src/main/java/soconnect/MainApp.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/ReadOnlySoConnect.java
  src/main/java/soconnect/model/SoConnect.java
  src/main/java/soconnect/model/tag/UniqueTagList.java
  src/main/java/soconnect/model/util/SampleDataUtil.java
  src/main/java/soconnect/storage/JsonSerializableTodoList.java
  src/main/java/soconnect/storage/JsonTodoListStorage.java
  src/main/java/soconnect/storage/Storage.java
  src/main/java/soconnect/storage/StorageManager.java
  src/main/java/soconnect/storage/TodoListStorage.java
  src/test/java/soconnect/model/SoConnectTest.java
Labels: bug

#136 Bug Fix for DG UML and for TodoParser
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/soconnect/logic/parser/todo/TodoParser.java
Labels: bug, priority.Medium

#113 Improve autocomplete for multiple search
  src/main/java/soconnect/commons/util/StringUtil.java
  src/main/java/soconnect/logic/LogicManager.java
  src/main/java/soconnect/logic/autocomplete/Autocomplete.java
  src/main/java/soconnect/logic/autocomplete/AutocompleteManager.java
  src/main/java/soconnect/logic/commands/FindCommand.java
  src/main/java/soconnect/logic/parser/FindCommandParser.java
  src/main/java/soconnect/logic/parser/SoConnectParser.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/ui/CommandBox.java
  src/test/java/soconnect/logic/autocomplete/AutocompleteManagerTest.java
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/FindCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
  src/test/java/soconnect/logic/parser/FindCommandParserTest.java
  src/test/java/soconnect/logic/parser/SoConnectParserTest.java
  src/test/java/soconnect/testutil/SoConnectBuilder.java
Labels: enhancement, priority.High

#117 Improve relevant search and fix bugs
  src/main/java/soconnect/commons/util/StringUtil.java
  src/main/java/soconnect/logic/commands/SearchCommand.java
  src/main/java/soconnect/logic/parser/SearchCommandParser.java
  src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java
  src/test/java/soconnect/logic/commands/SearchCommandTest.java
  src/test/java/soconnect/logic/parser/SearchCommandParserTest.java
Labels: priority.High

#142 Fix GUI Bugs and Reorganize SoConnectTheme.css
  src/main/java/soconnect/ui/PersonCard.java
  src/main/java/soconnect/ui/TodoCard.java
  src/main/resources/view/SoConnectTheme.css
  src/main/resources/view/TodoListCard.fxml
Labels: priority.High

#151 Minor message fixes
  src/main/java/soconnect/logic/commands/customise/CustomiseCommand.java
  src/main/java/soconnect/logic/commands/customise/CustomiseHideCommand.java
  src/main/java/soconnect/logic/commands/customise/CustomiseOrderCommand.java
  src/main/java/soconnect/logic/commands/customise/CustomiseShowCommand.java
  src/main/java/soconnect/logic/parser/customise/CustomiseCommandParser.java
Labels: priority.Medium

#141 Add date to Todo
  src/main/java/soconnect/MainApp.java
  src/main/java/soconnect/logic/Logic.java
  src/main/java/soconnect/logic/LogicManager.java
  src/main/java/soconnect/logic/commands/todo/TodoAddCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoClearCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoEditCommand.java
  src/main/java/soconnect/logic/commands/todo/TodoShowCommand.java
  src/main/java/soconnect/logic/parser/CliSyntax.java
  src/main/java/soconnect/logic/parser/ParserUtil.java
  src/main/java/soconnect/logic/parser/todo/TodoAddCommandParser.java
  src/main/java/soconnect/logic/parser/todo/TodoEditCommandParser.java
  src/main/java/soconnect/logic/parser/todo/TodoShowCommandParser.java
  src/main/java/soconnect/model/Model.java
  src/main/java/soconnect/model/ModelManager.java
  src/main/java/soconnect/model/todo/Date.java
  src/main/java/soconnect/model/todo/Todo.java
  src/main/java/soconnect/model/todo/UniqueTodoList.java
  src/main/java/soconnect/model/todo/predicates/TodoContainsDatePredicate.java
  src/main/java/soconnect/model/todo/predicates/TodoContainsDateRangePredicate.java
  src/main/java/soconnect/model/todo/predicates/TodoContainsPriorityPredicate.java
  src/main/java/soconnect/model/todo/predicates/TodoContainsTagPredicate.java
  src/main/java/soconnect/model/util/SampleDataUtil.java
  src/main/java/soconnect/storage/JsonAdaptedTodo.java
  src/main/java/soconnect/storage/JsonSerializableTodoList.java
  src/main/java/soconnect/ui/MainWindow.java
  src/main/java/soconnect/ui/PersonListPanel.java
  src/main/java/soconnect/ui/TodoCard.java
  src/main/java/soconnect/ui/TodoListPanel.java
  src/main/resources/images/date_icon.png
  src/main/resources/images/priority_icon.png
  src/main/resources/view/SoConnectTheme.css
  src/main/resources/view/TodoListCard.fxml
  src/test/java/soconnect/logic/commands/AddCommandTest.java
  src/test/java/soconnect/logic/commands/SortCommandTest.java
Labels: enhancement, priority.High

#155 Release for v1.3
  src/main/java/soconnect/MainApp.java
Labels: priority.High

#218 Update User Guide Structure and PPP
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/team/pangkuangwei.md
Labels: bug, documentation, priority.High
